services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock