[project]
name = "css-tweaks"
version = "0.1.0"
description = "A minimal web UI for generating sharable Discord CSS tweak URLs."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "litestar[standard]>=2.16.0",
    "pygit2>=1.13.3",
    "types-pygit2>=1.15.0.20241020",
]
